import Head from "next/head";

function Header() {
  return (
    <>
      <Head>
        <title>X|V</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/063922_hr1.png" />
      </Head>
    </>
  );
}

export default Header;
