import Head from "next/head";

function Header() {
  return (
    <>
      <Head>
        <title>{/* <Image src="/1up.png"></Image> */}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}

export default Header;
